### ISSUE TITLE
Update to react 15

### ISSUE THREAD

**Issue by jtadmor** [mlaursen/react-dd-menu#32]
Hi,

We are looking to upgrade to react 15, but this library doesn't like that as a peer dependency. Any objections to a pull request making that change?

**Comment by mlaursen** [comment]
Feel free!

**Comment by mlaursen** [comment]
I had some time this weekend so I went ahead and updated the peer dependencies to allow React 15. Should be usable with an upgrade to 1.0.7

**Comment by jtadmor** [comment]
Awesome, thanks! We'll let you know if we notice anything funky.
